cpufreq_interactivex: include missing header file; uncomment the Makefile line for interactivex
Seriously, why is this here?

This fixes the compile/build time error complaining about MAX_RT_PRIO.

	error: 'MAX_RT_PRIO' undeclared (first use in this function)

And compiles interactivex governor by uncommenting the line in the Makefile.
Presumambly because it does not compile.

Signed-off-by: Mark Enriquez <enriquezmark36@gmail.com>